- name:  Copy MongoDB repo file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name:  Install MongoDB
  ansible.builtin.dnf:
    name: mongodb-org
    state: latest

- name:  Update MongoDB config file
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name:  Start MongoDB Service
  ansible.builtin.systemd_service:
    name: mongod
    state: restarted
    enabled: true

#https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_reuse_roles.html#role-directory-structure
#ansible.builtin.copy module is used to copy files. files folder under roles structure is used when we use copy module. Refer mongodb component – tasks – main.yml.
#ansible.builtin.template module is used to copy files and to pass variable value on them. when we use template module, we need to use templates folder under roles structure. Refer frontend component – tasks – main.yml
