- name: COpy Repo file
  ansible.builtin.copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

- name: Install rabbitmq server
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: latest

- name: Start RabbitMQ service
  ansible.builtin.systemd_service:
    name: rabbitmq-server
    state: restarted
    enabled: yes

- name: Create application user
  ansible.builtin.shell: rabbitmqctl add_user {{ secrets.AMQP_USER }} {{ secrets.AMQP_PASS }} ; rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"

#https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_reuse_roles.html#role-directory-structure
#ansible.builtin.copy module is used to copy files. files folder under roles structure is used when we use copy module. Refer mongodb component – tasks – main.yml.
#ansible.builtin.template module is used to copy files and to pass variable value on them. when we use template module, we need to use templates folder under roles structure. Refer frontend component – tasks – main.yml