# variable values are defined in vars - main.yml of relevant service folders

# use user module to add user
- name: Adding Application User
  ansible.builtin.user:
    name: roboshop

# use file module to remove a file
- name: Remove old content
  ansible.builtin.file:
    path: "{{ app_path }}"
    state: absent #used to remove content

# use file module to create a directory
- name: Create App Directory
  ansible.builtin.file:
    path: "{{ app_path }}"
    state: directory

# use unarchive module to download and unzip a file
- name: Download & Extract Application Content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}-v3.zip
    dest: "{{ app_path}}"
    remote_src: yes