- name: Install Maven and Java
  ansible.builtin.dnf:
    name: maven

- name: Setup App Prerequisites
  ansible.builtin.include_role: #to load another task from a role
    name: common
    tasks_from: app-prereq

- name: Download Dependencies
  ansible.builtin.shell: mvn clean package ;mv target/{{ component }}-1.0.jar {{ component }}.jar
  args:
    chdir: "{{ app_path }}" #used to cd

- name: Load Schema
  ansible.builtin.include_role: #to load another task from a role
    name: common
    tasks_from: schema
  when: schema_setup is defined
  #conditional used to load schema only when schema_setup is defined in a component

- name: SystemD setup
  ansible.builtin.include_role: #to load another task from a role
    name: common
    tasks_from: systemd