- name:  Disable NodeJS Default Version
  ansible.builtin.shell: dnf module disable nodejs -y

- name:  Enable NodejS 20 Module
  ansible.builtin.shell: dnf module enable nodejs:20 -y

- name:  Install Nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: latest

#to load another task from a role
- name: Setup App Prerequisites
  ansible.builtin.include_role:
    name: common
    tasks_from: app-prereq

# there could be a npm module, However we are still using shell, Since these steps will get removed when CI comes in.
- name:  Download NodeJS Dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: "{{ app_path }}"
    #used to cd

#to load another task from a role
- name: Load Schema
  ansible.builtin.include_role:
    name: common
    tasks_from: schema
  when: schema_setup is defined
  #conditional used to load schema only when schema_setup is defined in a component

#to load another task from a role
- name: SystemD setup
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd