#block is used for grouping
# when conditional used to load schema only when schema_setup is defined in a component
- name: Load MongoDB schema
  when: schema_setup == "mongo"
  block:
    - name: COpy MongoDB repo file
      ansible.builtin.template:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install MongoDB Client
      ansible.builtin.dnf:
        name: mongodb-mongosh
        state: latest

    - name: Load Master Data
      ansible.builtin.shell: mongosh --host mongo.{{ env }}.sridevops.site </app/db/{{ item }}.js
      loop: "{{schema_files}}"

      #similar to using for loop in shell, we are using loop in ansible. a variable schema_files is defined. item var comes with loop and is used instead of file var in shell
#conditional used to load schema only when schema_setup is defined in a component
- name: Load MySQL schema
  when: schema_setup == "mysql"
  block:
    - name: Install mysql Client
      ansible.builtin.dnf:
        name: mysql
        state: latest

    - name: Load Master Data
      ansible.builtin.shell: mysql -h mysql.{{ env }}.sridevops.site -uroot -pRoboShop@1 < /app/db/{{ item }}.sql
      loop: "{{schema_files}}"

      #similar to using for loop in shell, we are using loop in ansible. a variable schema_files is defined. item var comes with loop